import type { Metadata } from "next";

const LAST_UPDATED = "April 21, 2026";

export const metadata: Metadata = {
  title: "Privacy Policy — Molecule AI",
  description:
    "How Molecule AI collects, uses, stores, and protects your personal data.",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <h1 className="text-4xl font-bold tracking-tight text-white">
        Privacy Policy
      </h1>
      <p className="mt-2 text-sm text-zinc-500">
        Last updated: {LAST_UPDATED}
      </p>

      <p className="mt-6 text-zinc-300">
        Molecule AI, Inc. (&ldquo;Molecule AI,&rdquo; &ldquo;we,&rdquo;
        &ldquo;us,&rdquo; or &ldquo;our&rdquo;) operates the Molecule AI
        platform at{" "}
        <a
          href="https://moleculesai.app"
          className="text-blue-400 underline hover:text-blue-300"
        >
          moleculesai.app
        </a>
        , including the canvas application, API, and associated services
        (collectively, the &ldquo;Service&rdquo;). This Privacy Policy
        describes how we collect, use, store, and share information when you
        use the Service.
      </p>

      {/* ------------------------------------------------------------ */}
      <Section title="1. Information We Collect">
        <Subsection title="1.1 Account Information">
          <p>
            When you sign up, we collect your name, email address, and
            authentication credentials. If you sign in via a third-party
            provider (e.g., GitHub OAuth), we receive the profile information
            that provider shares, which typically includes your username,
            email, and avatar URL.
          </p>
        </Subsection>

        <Subsection title="1.2 Organization and Workspace Data">
          <p>
            Molecule AI is an agent orchestration platform. When you create
            organizations and workspaces, we store your configuration data,
            system prompts, agent definitions, plugin settings, and workspace
            metadata. We also store activity logs generated by your AI agent
            workspaces, including prompts sent to language model providers and
            the responses received.
          </p>
        </Subsection>

        <Subsection title="1.3 Integrations">
          <p>
            If you connect third-party services (such as GitHub, Slack, or
            other tools), we store the access tokens and relevant metadata
            needed to maintain those connections. We access third-party
            service data only as necessary to operate the integrations you
            configure.
          </p>
        </Subsection>

        <Subsection title="1.4 Usage and Technical Data">
          <p>
            We automatically collect technical information such as your IP
            address, browser type, operating system, pages visited, and
            timestamps. This data helps us maintain security, debug issues,
            and improve the Service.
          </p>
        </Subsection>

        <Subsection title="1.5 Cookies">
          <p>
            We use strictly-necessary cookies for authentication and session
            management. Optional functional cookies (e.g., layout preferences,
            recent workspaces) are set only after you provide consent via our
            cookie banner. We do not use third-party advertising cookies. See
            our cookie banner for controls.
          </p>
        </Subsection>
      </Section>

      {/* ------------------------------------------------------------ */}
      <Section title="2. How We Use Your Information">
        <ul className="mt-3 list-disc space-y-2 pl-5 text-zinc-300">
          <li>
            <strong className="text-zinc-100">Provide and operate the Service</strong>{" "}
            — provisioning workspaces, executing agent tasks, routing
            messages between agents and integrations.
          </li>
          <li>
            <strong className="text-zinc-100">Process LLM requests</strong>{" "}
            — forwarding prompts to language model providers (e.g., OpenAI,
            Anthropic, Google) on your behalf and returning the responses to
            your workspaces.
          </li>
          <li>
            <strong className="text-zinc-100">Billing and usage metering</strong>{" "}
            — tracking compute time, token usage, and API calls for
            subscription and overage billing.
          </li>
          <li>
            <strong className="text-zinc-100">Security and abuse prevention</strong>{" "}
            — detecting unauthorized access, rate-limiting, and enforcing
            acceptable-use policies.
          </li>
          <li>
            <strong className="text-zinc-100">Improve the Service</strong>{" "}
            — analyzing aggregated, de-identified usage patterns to fix bugs
            and develop new features.
          </li>
          <li>
            <strong className="text-zinc-100">Communicate with you</strong>{" "}
            — sending transactional emails (account confirmations, security
            alerts, billing notices) and, with your consent, product updates.
          </li>
        </ul>
      </Section>

      {/* ------------------------------------------------------------ */}
      <Section title="3. Third-Party Services and Data Sharing">
        <p>
          We share your data with third parties only as necessary to operate
          the Service:
        </p>
        <ul className="mt-3 list-disc space-y-2 pl-5 text-zinc-300">
          <li>
            <strong className="text-zinc-100">LLM Providers</strong> (OpenAI,
            Anthropic, Google, and others you configure) — we forward your
            agent prompts and receive completions. Each provider&rsquo;s
            privacy policy governs their handling of that data.
          </li>
          <li>
            <strong className="text-zinc-100">Cloud Infrastructure</strong>{" "}
            (AWS, Vercel, Railway) — your workspace containers and platform
            services run on these providers. Data is stored in AWS us-east-2
            (Ohio, United States) unless otherwise specified.
          </li>
          <li>
            <strong className="text-zinc-100">Payment Processor</strong>{" "}
            (Stripe) — billing information is handled directly by Stripe. We
            do not store your full payment card details.
          </li>
          <li>
            <strong className="text-zinc-100">Integration Partners</strong>{" "}
            (GitHub, Slack, and others you connect) — data flows to these
            services only when you explicitly configure and enable
            integrations.
          </li>
        </ul>
        <p className="mt-3">
          We do not sell your personal data. We do not share your data with
          third parties for their own marketing purposes.
        </p>
      </Section>

      {/* ------------------------------------------------------------ */}
      <Section title="4. Data Storage and Security">
        <p>
          Your data is stored on infrastructure hosted in the United States
          (primarily AWS us-east-2). We implement industry-standard security
          measures including encryption in transit (TLS), encryption at rest
          for databases and storage volumes, and role-based access controls.
          Workspace containers are isolated per-organization.
        </p>
        <p className="mt-3">
          No system is completely secure. We cannot guarantee absolute
          security, but we take commercially reasonable steps to protect your
          data and promptly address any incidents.
        </p>
      </Section>

      {/* ------------------------------------------------------------ */}
      <Section title="5. Data Retention">
        <p>
          We retain your account data for as long as your account is active.
          Activity logs (agent prompts, responses, and execution metadata) are
          retained for 90 days by default unless your plan specifies a
          different retention period. When you delete a workspace or
          organization, associated data is scheduled for deletion within 30
          days. You can request immediate deletion by contacting us.
        </p>
        <p className="mt-3">
          We may retain limited, de-identified data for aggregate analytics
          and service improvement after deletion of your account.
        </p>
      </Section>

      {/* ------------------------------------------------------------ */}
      <Section title="6. Your Rights">
        <p>
          Depending on your jurisdiction, you may have the following rights
          regarding your personal data:
        </p>
        <ul className="mt-3 list-disc space-y-2 pl-5 text-zinc-300">
          <li>
            <strong className="text-zinc-100">Access</strong> — request a
            copy of the personal data we hold about you.
          </li>
          <li>
            <strong className="text-zinc-100">Rectification</strong> — ask us
            to correct inaccurate or incomplete data.
          </li>
          <li>
            <strong className="text-zinc-100">Erasure</strong> — request
            deletion of your personal data, subject to legal retention
            requirements.
          </li>
          <li>
            <strong className="text-zinc-100">Data Portability</strong> —
            receive your data in a structured, machine-readable format.
          </li>
          <li>
            <strong className="text-zinc-100">Restriction / Objection</strong>{" "}
            — restrict or object to certain processing activities.
          </li>
          <li>
            <strong className="text-zinc-100">Withdraw Consent</strong> —
            where processing is based on consent, you may withdraw it at any
            time.
          </li>
        </ul>
        <p className="mt-3">
          To exercise any of these rights, email us at{" "}
          <a
            href="mailto:privacy@moleculesai.app"
            className="text-blue-400 underline hover:text-blue-300"
          >
            privacy@moleculesai.app
          </a>
          . We will respond within 30 days.
        </p>
      </Section>

      {/* ------------------------------------------------------------ */}
      <Section title="7. International Data Transfers">
        <p>
          If you are located outside the United States, your data will be
          transferred to and processed in the United States. We rely on
          standard contractual clauses or other lawful transfer mechanisms
          where required by applicable data protection laws (including GDPR).
        </p>
      </Section>

      {/* ------------------------------------------------------------ */}
      <Section title="8. Children's Privacy">
        <p>
          The Service is not intended for individuals under the age of 16. We
          do not knowingly collect personal data from children. If we learn
          that we have collected data from a child under 16, we will delete it
          promptly.
        </p>
      </Section>

      {/* ------------------------------------------------------------ */}
      <Section title="9. Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. When we make
          material changes, we will notify you by posting a notice on the
          Service or sending you an email. Your continued use of the Service
          after changes take effect constitutes acceptance of the updated
          policy.
        </p>
      </Section>

      {/* ------------------------------------------------------------ */}
      <Section title="10. Contact Us">
        <p>
          If you have questions or concerns about this Privacy Policy or our
          data practices, contact us at:
        </p>
        <address className="mt-3 not-italic text-zinc-300">
          Molecule AI, Inc.
          <br />
          Email:{" "}
          <a
            href="mailto:privacy@moleculesai.app"
            className="text-blue-400 underline hover:text-blue-300"
          >
            privacy@moleculesai.app
          </a>
          <br />
          General inquiries:{" "}
          <a
            href="mailto:contact@moleculesai.app"
            className="text-blue-400 underline hover:text-blue-300"
          >
            contact@moleculesai.app
          </a>
        </address>
      </Section>
    </>
  );
}

/* ------------------------------------------------------------------ */
/*  Helper components — keep the JSX above readable                   */
/* ------------------------------------------------------------------ */

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-10">
      <h2 className="text-xl font-semibold text-white">{title}</h2>
      <div className="mt-3 text-zinc-300 leading-relaxed">{children}</div>
    </section>
  );
}

function Subsection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mt-4">
      <h3 className="text-base font-medium text-zinc-100">{title}</h3>
      <div className="mt-1.5 text-zinc-300 leading-relaxed">{children}</div>
    </div>
  );
}
