#!/usr/bin/env bash
#────────────────────────────────────────────────────────────────────────────
# Cloudflare Artifacts — Interactive Demo Script
# Molecule AI × Cloudflare Artifacts integration
#
# Prerequisites:
#   - Molecule AI platform (self-hosted or cloud)
#   - CF_ARTIFACTS_API_TOKEN      — Cloudflare API token with Artifacts write scope
#   CF_ARTIFACTS_NAMESPACE       — Cloudflare Artifacts namespace ID
#   PLATFORM_URL                 — e.g. https://platform.moleculesai.app
#   WORKSPACE_TOKEN              — Bearer token for the workspace
#   WORKSPACE_ID                 — Target workspace ID
#
# What this demo covers:
#   Step 1 — Attach a new Artifacts repo to a workspace via API
#   Step 2 — Mint a short-lived git credential
#   Step 3 — Clone, write a file, commit, and push
#   Step 4 — Fork the repo for an experiment branch
#   Step 5 — Clean up
#
# Run: bash demo.sh
#────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
PLATFORM_URL="${PLATFORM_URL:-https://platform.moleculesai.app}"
WORKSPACE_TOKEN="${WORKSPACE_TOKEN:-}"
WORKSPACE_ID="${WORKSPACE_ID:-}"
DEMO_DIR="${DEMO_DIR:-$(mktemp -d)}"
REPO_NAME="demo-$(date +%s)"
CURL_FLAGS=(-s -f)

# ── Helpers ─────────────────────────────────────────────────────────────────
log()  { echo "[$(date +%H:%M:%S)] $*"; }
step() { echo ""; echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"; echo "  STEP $1: $2"; echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"; }
warn() { echo "[WARN] $*" >&2; }
die()  { echo "[ERROR] $*" >&2; exit 1; }

# ── Env validation ───────────────────────────────────────────────────────────
if [[ -z "$WORKSPACE_TOKEN" || -z "$WORKSPACE_ID" ]]; then
  die "WORKSPACE_TOKEN and WORKSPACE_ID must be set. See README.md for setup."
fi

AUTH_HDR="Authorization: Bearer $WORKSPACE_TOKEN"
CT_HDR="Content-Type: application/json"

# ── Step 0: Probe the platform ──────────────────────────────────────────────
step 0 "Probe platform health"
log "Platform: $PLATFORM_URL"
STATUS_CODE=$(curl "${CURL_FLAGS[@]}" -o /dev/null -w "%{http_code}" \
  "$PLATFORM_URL/health" 2>/dev/null || echo "000")
if [[ "$STATUS_CODE" != "200" && "$STATUS_CODE" != "401" ]]; then
  warn "Platform not reachable (HTTP $STATUS_CODE) — continuing anyway if auth works"
else
  log "Platform reachable (HTTP $STATUS_CODE)"
fi

# ── Step 1: Attach a new Artifacts repo ─────────────────────────────────────
step 1 "Attach a new Artifacts repo to workspace $WORKSPACE_ID"

RESPONSE=$(curl "${CURL_FLAGS[@]}" -X POST \
  "$PLATFORM_URL/workspaces/$WORKSPACE_ID/artifacts" \
  -H "$AUTH_HDR" \
  -H "$CT_HDR" \
  -d "$(cat <<EOF
{
  "name": "$REPO_NAME",
  "description": "Agent demo workspace — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
)")

if ! echo "$RESPONSE" | jq -e '.id' > /dev/null 2>&1; then
  die "Failed to create repo. Response:\n$RESPONSE"
fi

REPO_ID=$(echo "$RESPONSE" | jq -r '.id')
REMOTE_URL=$(echo "$RESPONSE" | jq -r '.remote_url')
log "Repo created:"
log "  id         : $REPO_ID"
log "  name       : $REPO_NAME"
log "  remote_url : $REMOTE_URL"

# ── Step 2: Mint a short-lived git credential ────────────────────────────────
step 2 "Mint a short-lived git credential"

TOKEN_RESP=$(curl "${CURL_FLAGS[@]}" -X POST \
  "$PLATFORM_URL/workspaces/$WORKSPACE_ID/artifacts/token" \
  -H "$AUTH_HDR")

if ! echo "$TOKEN_RESP" | jq -e '.token' > /dev/null 2>&1; then
  die "Failed to mint credential. Response:\n$TOKEN_RESP"
fi

GIT_USER=$(echo "$TOKEN_RESP" | jq -r '.username // "x"')
GIT_PASS=$(echo "$TOKEN_RESP" | jq -r '.token')
log "Credential minted (username=$GIT_USER, token=***${GIT_PASS: -6})"

# ── Step 3: Clone, write, commit, push ───────────────────────────────────────
step 3 "Clone repo · write agent snapshot · commit · push"

WORK_DIR="$DEMO_DIR/$REPO_NAME"
mkdir -p "$WORK_DIR"

# Swap embedded credential for fresh token
SAFE_REMOTE=$(echo "$REMOTE_URL" | sed 's|//[^@]*@|//'"$GIT_USER"':'"$GIT_PASS"'@|')
git clone --quiet "$SAFE_REMOTE" "$WORK_DIR" 2>/dev/null || {
  # Bare repo — initialise
  git init "$WORK_DIR" --quiet
  git -C "$WORK_DIR" remote add origin "$SAFE_REMOTE" 2>/dev/null || true
}

cd "$WORK_DIR"
git config user.email "agent@molecule.ai" 2>/dev/null || true
git config user.name  "Molecule AI Agent"  2>/dev/null || true

# Write an agent snapshot (simulates agent work output)
cat > AGENT_SNAPSHOT.md <<'SNAPSHOT'
# Agent Run — generated by Molecule AI demo

## Task Summary
- Target: demonstrate Cloudflare Artifacts git workflow
- Actions: repo attach, credential mint, clone, commit, push

## Changes
- Added AGENT_SNAPSHOT.md with this run log

## Status
Complete. Repo is versioned and pushable.
SNAPSHOT

git add AGENT_SNAPSHOT.md
git commit -quiet -m "feat: agent run snapshot — Cloudflare Artifacts demo"
git push -q origin main 2>/dev/null && log "Push succeeded" || log "Push skipped (empty remote — first commit is local only)"

log "Files in working tree:"
git ls-files

# ── Step 4: Fork the repo ────────────────────────────────────────────────────
step 4 "Fork the repo for an experiment branch"

FORK_NAME="${REPO_NAME}-experiment"
FORK_RESP=$(curl "${CURL_FLAGS[@]}" -X POST \
  "$PLATFORM_URL/workspaces/$WORKSPACE_ID/artifacts/fork" \
  -H "$AUTH_HDR" \
  -H "$CT_HDR" \
  -d "$(cat <<EOF
{
  "name": "$FORK_NAME",
  "description": "Experiment fork — testing alternate snapshot format"
}
EOF
)")

if ! echo "$FORK_RESP" | jq -e '.id' > /dev/null 2>&1; then
  warn "Fork endpoint not available (HTTP $(curl -s -o /dev/null -w '%{http_code}' \
    -X POST "$PLATFORM_URL/workspaces/$WORKSPACE_ID/artifacts/fork" \
    -H "$AUTH_HDR" -H "$CT_HDR" -d '{}')). Skipping fork step."
  log "To fork manually, use: curl -X POST $PLATFORM_URL/workspaces/$WORKSPACE_ID/artifacts/fork"
else
  FORK_ID=$(echo "$FORK_RESP" | jq -r '.id')
  FORK_URL=$(echo "$FORK_RESP" | jq -r '.remote_url')
  log "Fork created: id=$FORK_ID"
  log "  fork remote : ${FORK_URL:0:60}..."
  log "  next step   : git clone <fork_url> && cd <repo> && git push"
fi

# ── Step 5: Show repo state ───────────────────────────────────────────────────
step 5 "Verify — list workspace Artifacts repos"

VERIFY=$(curl "${CURL_FLAGS[@]}" \
  "$PLATFORM_URL/workspaces/$WORKSPACE_ID/artifacts" \
  -H "$AUTH_HDR")

log "Current workspace repos:"
echo "$VERIFY" | jq -r '.repos[] | "  \(.id)  \(.name)  (\(.created_at[:10])), remote: \(.remote_url[:50])..."'

# ── Cleanup ──────────────────────────────────────────────────────────────────
step X "Cleanup"
log "Removing demo directory: $DEMO_DIR"
rm -rf "$DEMO_DIR"
log "Done. Demo complete."
echo ""
log "Next: run a real agent workflow — clone the repo in your agent's context,"
log "      make changes, and push. Every agent run becomes a Git commit."
