#!/bin/bash
# Run this script to create the Phase 34 marketing content PR.
# Requires a working GH_TOKEN / gh auth.
# Marketing Lead GH_TOKEN is 401 in this workspace — Social Media Brand
# or mol-ops should run this.
#
# Generated by Marketing Lead 2026-04-23

set -e

cd "$(git rev-parse --show-toplevel)"

gh pr create \
  --base staging \
  --head marketing/phase-34-launch-prep \
  --title "Phase 34 launch prep: Tool Trace, Platform Instructions, Partner API Keys, SaaS Fed v2 marketing content" \
  --body "$(cat <<'EOF'
## Summary

31 commits of Phase 34 launch marketing content for the April 30, 2026 GA launch.

### Includes

- **Blog posts** (5 new): A2A enterprise deep-dive, MCP server list, EC2 SSH terminal, Partner API Keys GA, Tool Trace + Platform Instructions
- **Social copy queue** (Apr 24–Apr 30): full 7-day coverage before and through GA
- **Launch posts**: HN Show HN, Reddit r/MachineLearning + r/LocalLLaMA
- **Community content**: Phase 34 announcement, community FAQ (14 Q&A), Discord runbook
- **DevRel**: talk-track (5-min script with timing markers), partner API keys demo
- **Battlecard + SEO brief**: Partner API Keys competitive battlecard, Phase 34 SEO brief
- **Partner onboarding guide**: with GitHub Actions CI/CD YAML (ephemeral org per PR)
- **Social channels**: Phase 34 preview social copy (Apr 27–29)
- **og:image**: Added to 13 blog posts missing OG images (batch script)

### Critical fixes

**Enterprise gating error corrected** — Platform Instructions has zero plan/tier gate (confirmed by code review of `workspace-server/internal/handlers/instructions.go`, no `requireEnterprise()` anywhere in the handler). Three canonical blog posts incorrectly claimed "enterprise-only" — all fixed:
- `docs/blog/2026-04-23-tool-trace-platform-instructions/index.md`
- `docs/blog/2026-04-23-platform-instructions-governance/index.md`
- `docs/blog/2026-04-23-partner-api-keys.md`

Documented at `docs/marketing/briefs/platform-instructions-plan-gating-note.md`.

### Requires PM decision before April 30 publish

`docs/marketing/briefs/phase34-ga-vs-beta-conflict.md` — internal positioning brief and messaging matrix say BETA/Do-not-claim-GA for all Phase 34 features; all approved external launch assets say "GA today." PM or PMM must confirm authoritative launch label. If Beta, 7 files need editing (listed in the brief).

### Rate limits / SaaS Fed v2

`[RATE LIMIT TBD]` placeholder in partner-onboarding-guide.md — PM to confirm from molecule-controlplane.
SaaS Fed v2 battlecard parked — no implementation found in molecule-core, PM to confirm details.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
EOF
)"

echo "PR created successfully."
