version: 4

linters:
  default: none
  enable:
    - staticcheck
    - gofmt
    - govet

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: false
    disable:
      - errcheck

run:
  timeout: 3m
  tests: true